src/Entity/Films.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FilmsRepository")
 */
class Films
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Titre;

    /**
     * @ORM\Column(type="date")
     */
    private $Annee;

    /**
     * @ORM\Column(type="time")
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $synopsys;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disponibilite;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAnnee(): ?\DateTimeInterface
    {
        return $this->Annee;
    }

    public function setAnnee(\DateTimeInterface $Annee): self
    {
        $this->Annee = $Annee;

        return $this;
    }

    public function getDuree(): ?\DateTimeInterface
    {
        return $this->duree;
    }

    public function setDuree(\DateTimeInterface $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getSynopsys(): ?string
    {
        return $this->synopsys;
    }

    public function setSynopsys(string $synopsys): self
    {
        $this->synopsys = $synopsys;

        return $this;
    }

    public function getDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    

    /**
     * @return Collection|user[]
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(user $user): self
    {
        if (!$this->user->contains($user)) {
            $this->user[] = $user;
            $user->setFilm($this);
        }

        return $this;
    }

    public function removeUser(user $user): self
    {
        if ($this->user->contains($user)) {
            $this->user->removeElement($user);
            // set the owning side to null (unless already changed)
            if ($user->getFilm() === $this) {
                $user->setFilm(null);
            }
        }

        return $this;
    }

    public function getPanier(): ?Panier
    {
        return $this->panier;
    }

    public function setPanier(?Panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }
}

src/Form/FilmType.php
<?php

namespace App\Form;

use App\Entity\Films;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FilmType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title')
            ->add('Year')
            ->add('Runtime')
            ->add('Poster')
            ->add('Plot')
            ->add('Released')
            ->add('Genre')
            ->add('Director')
            ->add('Language')
            ->add('Country')
            ->add('Awards')
            ->add('Type')
            ->add('DVD')
            ->add('Production')        

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class'=> Films::class
            // Configure your form options here
        ]);
    }
}

src/Controller/FilmsController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Films;

class FilmsController extends AbstractController
{
	/**
	* @Route("/", name="visitor")
	*/
	public function visitor(){
		return $this->render('films/visitor.html.twig', [
			'title' => "Bonjour, si vous souhaitez avoir accès à nos films en location, merci de vous identifier"
		]);
	}

	/**
	* @Route("/home", name="home")
	*/
	public function home(){

		$repo = $this->getDoctrine()->getRepository(Films::class);

        $film = $repo->findAll();

		return $this->render('films/home.html.twig', [
			'title' => "Bienvenue sur notre site de location de Films",
			'controller_name' => 'FilmsController',
            'films' => $film,
		]);

	}

    /**
     * @Route("/films", name="films")
     */
    public function index()
    {
   
       
    }
}

templates/films/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <section class="films">
        {% for film in films %}
            <div>
                <h2>{{ film.titre }}</h2>
                <div class="metadata"> Film publié le {{ film.annee | date('d/m/Y')}} et dure {{ film.duree | date('H:i')}} heures</div>
                <img src="{{ film.image }}" alt="tutodidacte" />
                {{ film.synopsys | raw }}
                <p>2€</p>
                <p>Disponible en rayon : {{ film.disponibilite }}</p>
                {% if film.disponibilite == true %}
                    <a href="{{ path('cart_add', {'id' : film.id}) }}"<button type="button" class="btn btn-success"> Ajouter à mon panier </button></a>
                {% else %}
                    <input type="button" value="Film indisponible" disabled="disabled">
                {% endif %}
            </div>
        {% endfor %}
    </section>
    
{% endblock %}

templates/films/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FilmsController!{% endblock %}

{% block body %}
<form action={{ path('apicall')}} method=post>
            <input id="search_films" name="search_films"type="search" placeholder="Taper le nom d'un film">
            <button type=submit >Rechercher</button>
</form>
{% endblock %}

templates/films/visitor.html.twig
{% extends "/base.html.twig" %}

{% block body %}
<h1> {{ title }} </h1>
<section class="d-flex justify-content-around">
<div class="border border-success rounded-pill">
	<a href="#">Connexion</a>
</div>
<div class="border border-warning rounded-pill">
	<a href="#">Inscription</a>
</div>
</section>
{% endblock %}