src/Entity/Movie.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MovieRepository")
 */
class Movie
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

     /**
     * @ORM\Column(type="string", length=255)
     */
  
    private $Title;

    /**
     * @ORM\Column(type="date")
     */
    private $Year;

    /**
     * @ORM\Column(type="time")
     */
    private $Runtime;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Poster;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Plot;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Released;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Genre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Director;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Language;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Country;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Awards;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $DVD;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Production;

    /**
     * @ORM\Column(type="boolean")
     */
    private $disponibilite;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="movies")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="Panier", inversedBy="movies")
     */
    private $panier;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Titre = $Title;

        return $this;
    }

    public function getYear(): ?string
    {
        return $this->Year;
    }

    public function setYear(string $Year): self
    {
        $this->Year = $Year;

        return $this;
    }

    public function getRuntime(): ?string
    {
        return $this-> Runtime;
    }

    public function setRuntime(string $Runtime): self
    {
        $this->duree = $Runtime;

        return $this;
    }

    public function getPoster(): ?string
    {
        return $this->Poster;
    }

    public function setPoster(string $Poster): self
    {
        $this->Poster = $Poster;

        return $this;
    }

    public function getPlot(): ?string
    {
        return $this->Plot;
    }

    public function setPlot(string $Plot): self
    {
        $this->Plot = $Plot;

        return $this;
    }

    public function getReleased(): ?string
    {
        return $this->Released;
    }

    public function setReleased(string $Released): self
    {
        $this->Released = $Released;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }
    public function getDirector(): ?string
    {
        return $this->Director;
    }

    public function setDirector(string $Director): self
    {
        $this->Director = $Director;

        return $this;
    }
    public function getLanguage(): ?string
    {
        return $this->Language;
    }

    public function setLanguage(string $Language): self
    {
        $this->Language = $Language;

        return $this;
    }
    public function getCountry(): ?string
    {
        return $this->Country;
    }

    public function setCountry(string $Country): self
    {
        $this->Country = $Country;

        return $this;
    }
    public function getAwards(): ?string
    {
        return $this->Awards;
    }

    public function setAwards(string $Awards): self
    {
        $this->Awards = $Awards;

        return $this;
    }
    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }
    public function getDVD(): ?string
    {
        return $this->DVD;
    }

    public function setDVD(string $DVD): self
    {
        $this->DVD = $DVD;

        return $this;
    }
    public function getProduction(): ?string
    {
        return $this->Production;
    }

    public function setProduction(string $Production): self
    {
        $this->Production = $Production;

        return $this;
    }

    public function getAvailable(): ?bool
    {
        return $this->disponibilite;
    }

    public function setAvailable(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    // public function setUser(?user $user): self
    // {
    //     $this->user = $user;

    //     return $this;
    // }

    public function getPanier(): ?panier
    {
        return $this->panier;
    }

    public function setPanier(?panier $panier): self
    {
        $this->panier = $panier;

        return $this;
    }
}

src/Controller/MoviesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Movie;

class MoviesController extends AbstractController
{
	/**
	* @Route("/", name="visitor")
	*/
	public function visitor(){
		return $this->render('movies/visitor.html.twig', [
			'title' => "Bonjour, si vous souhaitez avoir accès à nos films en location, merci de vous identifier"
		]);
	}

	/**
	* @Route("/home", name="home")
	*/
	public function home(){

		$repo = $this->getDoctrine()->getRepository(Movie::class);

        $movie = $repo->findAll();

		return $this->render('movies/home.html.twig', [
			'title' => "Bienvenue sur notre site de location de Films",
			'controller_name' => 'MoviesController',
            'films' => $movie,
		]);

	}
    /**
     * @Route("/movies", name="movies")
     */
    public function index()
    {
		return $this->render('movies/index.html.twig', [
            'controller_name' => 'MoviesController',
            ]);
    }
}

templates/movies/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <section class="films">
        {% for movie in movies %}
            <div>
                <h2>{{ movie.title }}</h2>
                <div class="metadata"> Film publié le {{ movie.year | date('d/m/Y')}} et dure {{ movie.runtime | date('H:i')}} heures</div>
                <img src="{{ film.image }}" alt="tutodidacte" />

                <!--REPRENDRE ICI MODIFE DE FILM A MOVIE
                    NE PAS OUBLIER DE MODIF LA BOUCLE FOR ENSUITE QUAND FIXTURES MOVIE FAITE !!!-->
                {{ film.synopsys | raw }}
                <p>2€</p>
                <p>Disponible en rayon : {{ movie.disponibilite }}</p>
                {% if movie.disponibilite == true %}
                    <a href="{{ path('cart_add', {'id' : movie.id}) }}"<button type="button" class="btn btn-success"> Ajouter à mon panier </button></a>
                {% else %}
                    <input type="button" value="Film indisponible" disabled="disabled">
                {% endif %}
            </div>
        {% endfor %}
    </section>
    
{% endblock %}

templates/movies/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Film{% endblock %}

{% block body %}
    <form action={{ path('apicall')}} method=post>
            <input id="search_movie" name="search_movie"type="search" placeholder="Taper le nom d'un film">
            <button type=submit >Rechercher</button>
    </form>
{#
    {{form_start(form)}}
    {{form_label(form.Title)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Year)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Runtime)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Poster)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Plot)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Release)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Genre)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Director)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Language)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Country)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Awards)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Type)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.DVD)}}
    {{form_end(form)}}
    {{form_start(form)}}
    {{form_label(form.Production)}}
    {{form_end(form)}}

    #}
{% endblock %}

templates/movies/visitor.html.twig
{% extends "/base.html.twig" %}

{% block body %}
<h1> {{ title }} </h1>
<section class="d-flex justify-content-around">
<div class="border border-success rounded-pill">
	<a href="#">Connexion</a>
</div>
<div class="border border-warning rounded-pill">
	<a href="#">Inscription</a>
</div>
</section>
{% endblock %}